### ISSUE TITLE
Comment faire pour faire d'autres fonctionnalités ?

### ISSUE THREAD

**Issue by AlthaelIsCoding** [Sworder71/Dashboard.io#1]
Pouvez vous mettre une documentation/compléter le README pour savoir comment faire pour ajouter autre chose que envoyer un message dans un salon précis.

Merci à vous !

**Comment by Androz2091** [comment]
Pour rajouter des commandes, il suffit de créer un nouveau fichier dans le dossier commandes et d'exporter une fonction run.

Pour modifier le CSS/JS c'est dans website/public.
Pour ajouter des boutons, il faut modifier les routes express (website/router) et modifier les views (website/views).
Si vous ne savez pas modifier les routes, suivez un tutoriel pour savoir comment marche express et si vous ne savez pas modifier les views, suivez un tutoriel pour savoir comment fonctionne les templates ejs.
J'espère que ça répond à votre question !
