### ISSUE TITLE
La redirection URI ne marche pas (configuré correctement)

### ISSUE THREAD

**Issue by Certurix** [Sworder71/Dashboard.io#11]
Bonjour.
Cela fait un moment que ce bug se produit de mon côté (je ne sais pas si cela le fait pour tout le monde) mais l'URI de redirection est incorrecte quand on clique sur les boutons de connexion sur la page d'accueil.

J'ai testé avec l'URI de redirection que Discord génère (dans le portail des développeurs, sur mon application). L'URI fonctionne, mais les données ne peuvent pas être envoyées car le code sur le dashboard n'a pas la même URL ..

Voici l'URL générée par Discord : (j'ai supprimé les données)
https://discordapp.com/oauth2/authorize?client_id=ID&redirect_uri=URI&response_type=code&scope=identify

Voici l'URL du site (quand on clique sur le bouton avec le /auth/login
https://discordapp.com/oauth2/authorize?response_type=code&redirect_uri=URI&scope=identify%20guilds&client_id=ID

Par ailleurs, je suis sûr que cela ne vient pas de moi, j'ai exactement mis l'URL d'authentification de mon site dans le OAuth2 URL Generator
![image](https://user-images.githubusercontent.com/46199479/73681698-3a5b9600-46bf-11ea-91d7-feff48981a6c.png)

Voici quelques screenshots pour mieux comprendre

Erreur quand on clique sur les deux boutons de connexions sur la page d'accueil
![image](https://user-images.githubusercontent.com/46199479/73681953-a3430e00-46bf-11ea-86e1-cbb65d768b7d.png)

Voilà, j'espère que vous résoudrez bientôt ce bug :)

**Comment by Certurix** [comment]
PS: Je viens de voir à l'instant qu'une issue a été ouverte au même sujet (#5) je le redit encore une fois, je suis sûr à 100% d'avoir configuré correctement la redirection

**Comment by Androz2091** [comment]
Bonjour,
Pourrais-tu envoyer l'URL de connexion vers laquelle le dashboard te redirige et l'URL entrée dans ta configuration oauth sur discord non floutées ? Cela permettrait de trouver efficacement le problème.

**Comment by Certurix** [comment]
Bonjour,

Voici l'URL de connexion du dashboard :
https://discordapp.com/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fcocitybot-dashboard.glitch.me%3A3000%2Fauth%2Flogin&scope=identify%20guilds&client_id=606044257522024449

Et voici l'URL entrée dans Oauth2 : 
https://cocitybot-dashboard.glitch.me/auth/login
![image](https://user-images.githubusercontent.com/46199479/73683408-7a704800-46c2-11ea-9965-ef6f4a0f8d93.png)

**Comment by Androz2091** [comment]
Ok, je vois d'où vient le problème. Si j'ai le temps je ferai une PR ce soir

**Comment by Certurix** [comment]
D'accord 👍 merci
