### ISSUE TITLE
"the redirect url is invalid" problem

### ISSUE THREAD

**Issue by Zaid-maker** [Sworder71/Dashboard.io#14]
before telling problem i want to thank to solve the previous problem of login now the problem is when i click on to login then it says **Redirect URL invalid** idk what is this i have double check everything and investigating how i got this error.

**Comment by Androz2091** [comment]
@Zaid-maker We need those informations to help you:

* your config file content (don't forget to remove private values like tokens)
* the redirect URLs you've allowed on discordapp.com/developers

**Comment by Sworder71** [comment]
Hi, did you fill the Oauth2 redirects form ?

**Comment by Zaid-maker** [comment]
# Oauth2 Link
**http://localhost:3000/login**

# The Config File
```json
{
	"bot": {
		"id": "588780580276011049",
		"prefix": ">",
		"secret": "",
		"status": "dnd",
		"token": "",
		"url": "http://localhost"
	},
	"app": {
		"port": 3000
	}
}
```

**Comment by Sworder71** [comment]
I meant in the developer portal of Discord

**Comment by Sworder71** [comment]
We need the OAuth2 redirects that you have filled on Developer Portal of Discord to help you.

**Comment by Sworder71** [comment]
So... in the new release of Dashboard.io, the login path is `/auth/login` instead of `/login`.

**Comment by Zaid-maker** [comment]
Yea Thank you i have fixed it i realized after i read the code again. Thank you
