### ISSUE TITLE
probleme avec OAuth2

### ISSUE THREAD

**Issue by lavablack2019** [Sworder71/Dashboard.io#15]
la OAuth2 ne marche pas meme si je met la redirection 

` https://negligibleexpensivewrapper--five-nine.repl.co/auth/login`

 dans le discord devloppeur

**Comment by Androz2091** [comment]
@Sworder71 C'est ce que permettait de régler ma PR. Lorsque les utilisateurs utilisent un nom de domaine (donc l'URL ne contient pas le port), ça cause une erreur de redirection. Je pense qu'il faudrait laisser une option dans la config pour ajouter une URL de callback personnalisée pour ces utilisateurs et par défaut, c'est une URL générée comme actuellement, non ?

**Comment by Sworder71** [comment]
@Androz2091 pourquoi pas. Il faudra donc créer les fields `custom_url` et `local_url`.

**Comment by Sworder71** [comment]
@lavablack2019 je ferai une mise à jour dans la semaine pour corriger cela, je clos donc cette issue.
