### ISSUE TITLE
Comment le mettre sur un site réel et pas en localhost

### ISSUE THREAD

**Issue by SnyGun** [Sworder71/Dashboard.io#3]
tout est dans le titre !

**Comment by Androz2091** [comment]
* Configure le nom de domaine pour qu'il pointe vers l'IP de ton serveur (ou celle de ton pc même si c'est pas conseillé)
* Lance le dashboard sur le port 3000 par exemple
* Configure Apache ou Nginx pour qu'il redirige les requêtes effectuées vers le nom de domaine sur `http://localhost:3000`
Et voilà
