### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RunyardHartley** [Sworder71/Dashboard.io#4]
Hi ! 

J'ai voulu utiliser le dashboard, mais le problème c'est qu'il ne fonctionne pas du tout avec shards ? C'est normal ? 

J'ai deux erreurs : adress in already in use : :::3000:::: mais aussi le bot redémarre sans cesse quand je met le petit await client.website.load(client) dans le ready.js.....

**Comment by Androz2091** [comment]
Bonjour @RunyardHartley !
Cette erreur apparait car tu dois déjà avoir une application qui tourne sur le port 3000. Cela peut être un autre logiciel, ou simplement dashboard.io, que tu aurais lancé plusieurs fois (ce qui est probable, ça arrive fréquemment de lancer plusieurs mêmes process nodejs sans le vouloir).
Tu peux utiliser la commande `netstat -a -b` pour obtenir la liste des process qui utilisent le port 3000.

Ensuite, tu peux soit redémarrer complètement ton ordinateur ou suivre ceci pour supprimer les process qui utilisent le port 3000.

Finalement, redémarre dashboard.io

**Comment by RunyardHartley** [comment]
Re ! Je suis sur Debian9 et la commande netstat ne se reconnaît pas.

**Comment by Androz2091** [comment]
Tape `apt install net-tools`. Quand tu as une erreur comme celle-là non liée directement à ce repo, tu peux chercher sur Google.

**Comment by RunyardHartley** [comment]
Re, j'ai essayé mais ça me met : netstat : option invalide -- 'b' j'ai cherché sur Google mais j'ai pas trouver grand chose

**Comment by RunyardHartley** [comment]
Re ! En faite la source de mon problème, c'est mes shards. Dans le tout premier shards le dashboard démarre sans problème, c'est quand c'est le deuxième shard et les autres que ce message d'erreur s'affiche... Je dois le mettre dans le shards.js ou ?

**Comment by Androz2091** [comment]
C'est exactement ce que je t'avais dit, tu essayes de lancer plusieurs fois une application sur le port 3000. A chaque shard, ton code lance le dashboard sur le port 3000. Le problème, c'est que si le shard 0 a déjà lancé le dashboard, le shard 1 ne va pas pouvoir le lancer car le port est déjà occupé.
Pour régler ça, une solution est de ne le lancer qu'au shard 0, comme ceci par exemple:
https://github.com/Androz2091/ManageInvite/blob/master/events/ready.js#L33 (code en v12 de discord.js)

**Comment by RunyardHartley** [comment]
Ah oui d'accord, mais je ne suis pas encore en v12 je suis à 11.5.1, donc si j'ai bien  comprit ce bout de code : 

if(this.client.shard.ids.includes(0) && !this.client.spawned){
            this.client.dash.load(this.client);
        }

Règle le problème ?

**Comment by Androz2091** [comment]
Oui, en v11.5 ça donne:
```Js
if(this.client.shard.id === 0){
	// load le dashboard
}
```
Bien sur il faut que tu l'adaptes au code de dashboard.io

**Comment by RunyardHartley** [comment]
Okay merci, faut je re modifie tout le monde de dashboard.js alors ?

**Comment by RunyardHartley** [comment]
Du coup, je viens de le mettre dans server.js et ça fonctionne je suis obligé de le mettre dans ready ?

**Comment by RunyardHartley** [comment]
J'ai réussi merci bien !
