### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ValWasBetter** [Sworder71/Dashboard.io#5]
Bonjour, j'ai tout suivi correctement et quand j'appuye sur Se Connecter ça me dit sa:
![image](https://user-images.githubusercontent.com/38843701/73016241-ca772100-3e1d-11ea-8869-035c99f30f6e.png)

**Comment by Androz2091** [comment]
@ValWasBetter est-ce que tu as bien suivi cette partie du readme?
https://github.com/Sworder71/Dashboard.io#fonctionnement
Si non, le problème vient de là.
Si oui, est-il possible de prendre un screenshot de ta configuration oauth2 et d'envoyer l'URL vers laquelle tu es redirigé au moment de la connexion (l'url de la page ou tu dois cliquer sur autoriser) ?

**Comment by ValWasBetter** [comment]
Ah c'bon, j'ai oublier juste d'ajouter le /login à la fin ^^

**Comment by Androz2091** [comment]
👌 Tu peux fermer l'issue alors

**Comment by Sworder71** [comment]
Je vais remettre ce projet à jour bientôt.

**Comment by Androz2091** [comment]
👍
